-- /* https://github.com/GomezMig03 */  #

-- This is a file where you put your own default apps, default search Engine etc

-- Set your default editor here uncomment and reboot to take effect.
-- NOTE, this will be automatically uncommented if you select neovim or vim to your default editor
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("EDITOR", "nvim")

-- Define preferred text editor for the KooL Quick Settings Menu (SUPER SHIFT E)
-- script will take the default EDITOR and nano as fallback
local edit = "${EDITOR:-nano}"

-- These two are for UserKeybinds.conf & Waybar Modules
local term = "kitty" -- Terminal
local files = "thunar" -- File Manager

-- Default Search Engine for ROFI Search (SUPER S)
local Search_Engine = "\"https://search.brave.com/search?q={}\""
