-- Generated by nwg-displays on 2026-08-14 at 10:19:33. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "6106x1080",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "8026x1080",
    scale = 1
})
hl.monitor({
    output = "DP-1",
    mode = "3840x2160@30.0",
    position = "2266x0",
    scale = 1
})
