-- Generated by nwg-displays on 2025-11-05 at 16:54:35. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-2",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
    default = true,
})

